// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    // apiKey: 'AIzaSyDfNbEUTyd9CvEb6YhbEAmYGS9au8qU2aQ',
    // appId: '1:762319130711:web:1e80b902f3716f75dc1312',
    // messagingSenderId: '762319130711',
    // projectId: 'renterii-application---v2',
    // authDomain: 'renterii-application---v2.firebaseapp.com',
    // storageBucket: 'renterii-application---v2.appspot.com',
    // measurementId: 'G-RDWR55ZBMJ',
    apiKey: "AIzaSyCEUv-1irHcq3LIpAt-Uhp08sXEiQnEITU",
  authDomain: "tworow-ai-web.firebaseapp.com",
  projectId: "tworow-ai-web",
  storageBucket: "tworow-ai-web.appspot.com",
  messagingSenderId: "250884608659",
  appId: "1:250884608659:web:a0edf46020edd622cef366",
  measurementId: "G-WP69550WDT"
  );
}
